# .github/workflows/deploy.yml
name: Deploy Portfolio to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 cp index.html s3://noahfrost-devsecops/
          aws s3 cp resume.pdf s3://noahfrost-devsecops/

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ERS9RIPIBIOR \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text

      - name: Display success message
        run: |
          echo "✅ Deployment complete!"
          echo "🌐 Site will be updated at https://noahfrost.co.uk in 2-5 minutes"